services:
  mysql:
    image: 'mysql:5.6'
    environment:
      - 'MYSQL_DATABASE=agregadordb'
      - 'MYSQL_PASSWORD=agregador123'
      - 'MYSQL_ROOT_PASSWORD=znmcizp0Ds'
      - 'MYSQL_USER=agregador'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: