version: '3.8'

services:
  postgres:
    image: 'postgres:16-alpine3.20'
    environment:
      POSTGRES_USER: agregador
      POSTGRES_PASSWORD: agregador123
      POSTGRES_DB: agregadordb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
