spring:
  application:
    name: agregadordeinvestimentos

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/agregadordb
    username: agregador
    password: agregador123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
